CREATE TABLE `codes` (
  `ID` varchar(36) NOT NULL,
  `CODE` varchar(10) NOT NULL,
  `TYPE` varchar(45) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  `CREATED_ON` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_ON` timestamp NULL DEFAULT NULL,
  `CREATED_BY` varchar(45) NULL DEFAULT NULL,
  `MODIFIED_BY` varchar(45) NULL DEFAULT NULL,  
  `ROW_STATUS` tinyint(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `address_info` (
  `ID` varchar(36) NOT NULL,
  `STREET_ADDRESS_1` varchar(45) NOT NULL,
  `STREET_ADDRESS_2` varchar(45) DEFAULT NULL,
  `STATE_ID` varchar(36) DEFAULT NULL,
  `PIN_CODE` int(6) DEFAULT NULL,
  `CREATED_ON` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED_ON` timestamp NULL DEFAULT NULL,
  `CREATED_BY` varchar(45) NULL DEFAULT NULL,
  `MODIFIED_BY` varchar(45) NULL DEFAULT NULL, 
  `ROW_STATUS` tinyint(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `FK_ADDRESS_STATE_idx` (`STATE_ID`),
  CONSTRAINT `FK_ADDRESS_STATE` FOREIGN KEY (`STATE_ID`) REFERENCES `codes` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `education_info` (
  `ID` varchar(36) NOT NULL,
  `COURSE_ID` varchar(36) NOT NULL,
  `COLLEGE_ID` varchar(36) NOT NULL,
  `PASSED_YEAR` timestamp NULL DEFAULT NULL,
  `PLACE` varchar(45) DEFAULT NULL,
  `CREATED_ON` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MODIFIED_ON` timestamp NULL DEFAULT NULL,
  `CREATED_BY` varchar(45) NULL DEFAULT NULL,
  `MODIFIED_BY` varchar(45) NULL DEFAULT NULL, 
  `ROW_STATUS` tinyint(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `FK_EDUCATION_COURCE_idx` (`COURSE_ID`),
  KEY `FK_EDUCATION_COLLEGE_idx` (`COLLEGE_ID`),
  CONSTRAINT `FK_EDUCATION_COURCE` FOREIGN KEY (`COURSE_ID`) REFERENCES `codes` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_EDUCATION_COLLEGE` FOREIGN KEY (`COLLEGE_ID`) REFERENCES `codes` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `person` (
  `ID` varchar(36) NOT NULL,
  `FIRST_NAME` varchar(45) NOT NULL,
  `LAST_NAME` varchar(45) NOT NULL,
  `DATE_OF_BIRTH` timestamp NULL DEFAULT NULL,
  `PHONE_NUMBER` int(10) DEFAULT NULL,
  `EDUCATION_INFO_ID` varchar(36) DEFAULT NULL,
  `ADDRESS_INFO_ID` varchar(36) DEFAULT NULL,
  `CREATED_ON` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `MODIFIED_ON` timestamp NULL DEFAULT NULL,
  `CREATED_BY` varchar(45) NULL DEFAULT NULL,
  `MODIFIED_BY` varchar(45) NULL DEFAULT NULL, 
  `ROW_STATUS` tinyint(4) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `FK_PERSON_EDUCATION_idx` (`EDUCATION_INFO_ID`),
  KEY `FK_PERSON_ADDRESS_idx` (`ADDRESS_INFO_ID`),
  CONSTRAINT `FK_PERSON_EDUCATION` FOREIGN KEY (`EDUCATION_INFO_ID`) REFERENCES `education_info` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_PERSON_ADDRESS` FOREIGN KEY (`ADDRESS_INFO_ID`) REFERENCES `address_info` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

